### ISSUE TITLE
Add a Menu [Feature Request]

### ISSUE THREAD

**Issue by ggedde** [Zeeker/sublime-GitConflictResolver#11]
I know that you allow for Keyboard Shortcuts, but it would be really nice if there was a Menu for the commands.  Like Tools -> Git Conflict Resolver -> {list of commands}

Honestly, I wont use this plugin that often. So I am not going to always remember which shortcut it is and I don't want to guess as I might do something else.  Would be nice it there was just a simple menu.

Thanks

**Comment by sascha-wolf** [comment]
There are the commands in the command palette. I could add menu entries just wanted to mention them.

**Comment by ggedde** [comment]
Thanks, I am just not use to the Command Palette.
ctrl/cmd  + shft + p
Then type in Git Conflict
