### ISSUE TITLE
Its blocking LALT+X => # shortcut

### ISSUE THREAD

**Issue by MiChAeLoKGB** [Zeeker/sublime-GitConflictResolver#12]
I think that's an issue of sublime text in general, but any shortcuts that require `ctrl+alt` can be ran with alt only. So basically every time I tried to comment a line in .htaccess I just got 

> Please select choices

I went trough all plugins and their key bindings and found nothing, so I started removing packages I don't really use, and after removing this one, it started to work normally again.

**Comment by sascha-wolf** [comment]
GitConflictResolver doesn't contain any default shortcuts to avoid any conflicts with the users shortcuts.

It's possible to add shortcuts on your own, as proposed in the README, but there are no shortcuts added unless you specifically did this yourself.

As such I'm sure that the plugin has nothing to do with the problem you described.

**Comment by MiChAeLoKGB** [comment]
Ok, there is something weird with my sublime... I clicked uninstall GitConflictResolver, but it uninstalled different package instead of this one and that fixed it... 

Well, consider this thread never existing.

**Comment by sascha-wolf** [comment]
I guarantee you that GitConflictResolver does not under any circumstances install default shortcuts. Any shortcuts related to GitConflictResolver have to be added manually.
