### ISSUE TITLE
Where is not a way to resolve conflicts line by line like the conflict resolver in WebStorm

### ISSUE THREAD

**Issue by SANGED** [Zeeker/sublime-GitConflictResolver#19]

**Comment by sascha-wolf** [comment]
Just edit the conflicts by hand; this tool is meant to be simple.

**Comment by SANGED** [comment]
@Zeeker the concern is that it would be just a little more interesting feature to see the 2 versions left and right, I do not know but I do not see how it would be so complex to develop
